# Generated by Django 5.0.6 on 2024-07-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_developer_skills_joboffer_required_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='subskills',
        ),
        migrations.AddField(
            model_name='competence',
            name='subskills',
            field=models.ManyToManyField(related_name='subskills', to='mainapp.competence'),
        ),
    ]
