# Generated by Django 5.0.6 on 2024-07-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_competence_subskills_competence_subskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='subskills',
            field=models.ManyToManyField(to='mainapp.competence'),
        ),
    ]
