# Generated by Django 5.0.6 on 2024-07-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_competence_subskills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='level',
        ),
    ]
