# Generated by Django 5.0.6 on 2024-07-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_competence_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='subskills',
            field=models.ManyToManyField(blank=True, to='mainapp.competence'),
        ),
    ]
