# Generated by Django 5.0.6 on 2024-07-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_competence_subskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
